/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "bds_index-histories": () => import("@/views/bds/index-histories/index.vue"),
  "bds_symbol-infos": () => import("@/views/bds/symbol-infos/index.vue"),
  "bds_trade-dates": () => import("@/views/bds/trade-dates/index.vue"),
  bills_bills: () => import("@/views/bills/bills/index.vue"),
  "bills_group-accs": () => import("@/views/bills/group-accs/index.vue"),
  "bills_group-symbols": () => import("@/views/bills/group-symbols/index.vue"),
  bills_group: () => import("@/views/bills/group/index.vue"),
  "bills_profit-years": () => import("@/views/bills/profit-years/index.vue"),
  bills_profits: () => import("@/views/bills/profits/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "irs_monitor-discounts": () => import("@/views/irs/monitor-discounts/index.vue"),
  "irs_monitor-option-ts": () => import("@/views/irs/monitor-option-ts/index.vue"),
  "irs_monitor-options": () => import("@/views/irs/monitor-options/index.vue"),
  "irs_symbol-discounts": () => import("@/views/irs/symbol-discounts/index.vue"),
  "irs_symbol-kpis": () => import("@/views/irs/symbol-kpis/index.vue"),
  "irs_symbol-options": () => import("@/views/irs/symbol-options/index.vue"),
  "irs_symbol-values": () => import("@/views/irs/symbol-values/index.vue"),
  "irs_value-monitor": () => import("@/views/irs/value-monitor/index.vue"),
};
