/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "bds_fund-data_finance-derivs": () => import("@/views/bds/fund-data/finance-derivs/index.vue"),
  "bds_fund-data_fund-balances": () => import("@/views/bds/fund-data/fund-balances/index.vue"),
  "bds_fund-data_fund-cashflows": () => import("@/views/bds/fund-data/fund-cashflows/index.vue"),
  "bds_fund-data_fund-incomes": () => import("@/views/bds/fund-data/fund-incomes/index.vue"),
  "bds_index-constituents": () => import("@/views/bds/index-constituents/index.vue"),
  "bds_macro-research_economic-dashboard": () => import("@/views/bds/macro-research/economic-dashboard/index.vue"),
  "bds_macro-research_economic-indicators": () => import("@/views/bds/macro-research/economic-indicators/index.vue"),
  "bds_macro-research_economic-report": () => import("@/views/bds/macro-research/economic-report/index.vue"),
  "bds_macro-research_gold-reserves": () => import("@/views/bds/macro-research/gold-reserves/index.vue"),
  "bds_macro-research_us-economic-dashboard": () => import("@/views/bds/macro-research/us-economic-dashboard/index.vue"),
  "bds_macro-research_us-yield-indicators": () => import("@/views/bds/macro-research/us-yield-indicators/index.vue"),
  "bds_market-data_daily-valuations": () => import("@/views/bds/market-data/daily-valuations/index.vue"),
  "bds_market-data_index-histories": () => import("@/views/bds/market-data/index-histories/index.vue"),
  "bds_symbol-infos": () => import("@/views/bds/symbol-infos/index.vue"),
  "bds_trade-dates": () => import("@/views/bds/trade-dates/index.vue"),
  bills_bills: () => import("@/views/bills/bills/index.vue"),
  "bills_group-accs": () => import("@/views/bills/group-accs/index.vue"),
  "bills_group-symbols": () => import("@/views/bills/group-symbols/index.vue"),
  bills_group: () => import("@/views/bills/group/index.vue"),
  "bills_profit-years": () => import("@/views/bills/profit-years/index.vue"),
  bills_profits: () => import("@/views/bills/profits/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "irs_discounts-monitor": () => import("@/views/irs/discounts-monitor/index.vue"),
  "irs_option_monitor-option-ts": () => import("@/views/irs/option/monitor-option-ts/index.vue"),
  "irs_option_monitor-options": () => import("@/views/irs/option/monitor-options/index.vue"),
  "irs_option_symbol-options": () => import("@/views/irs/option/symbol-options/index.vue"),
  "irs_value_symbol-kpis": () => import("@/views/irs/value/symbol-kpis/index.vue"),
  "irs_value_symbol-values": () => import("@/views/irs/value/symbol-values/index.vue"),
  "irs_value_value-monitor": () => import("@/views/irs/value/value-monitor/index.vue"),
};
