/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

// 手动调整为多级菜单结构，使用类型断言绕过严格的路由命名约定校验
export const generatedRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'bds',
    path: '/bds',
    component: 'layout.base',
    meta: {
      title: 'bds',
      i18nKey: 'route.bds',
      icon: 'mdi:database',
      order: 2,
      constant: true
    },
    children: [
      {
        name: 'bds_symbol-infos',
        path: '/bds/symbol-infos',
        component: 'view.bds_symbol-infos',
        meta: {
          title: 'bds_symbol-infos',
          i18nKey: 'route.bds_symbol-infos',
          constant: true
        }
      },
      {
        name: 'bds_trade-dates',
        path: '/bds/trade-dates',
        component: 'view.bds_trade-dates',
        meta: {
          title: 'bds_trade-dates',
          i18nKey: 'route.bds_trade-dates',
          constant: true
        }
      }
    ]
  },
  {
    name: 'bills',
    path: '/bills',
    component: 'layout.base',
    meta: {
      title: 'bills',
      i18nKey: 'route.bills',
      icon: 'mdi:currency-cny',
      order: 3,
      constant: true
    },
    children: [
      {
        name: 'bills_bills',
        path: '/bills/bills',
        component: 'view.bills_bills',
        meta: {
          title: 'bills_bills',
          i18nKey: 'route.bills_bills',
          constant: true
        }
      },
      {
        name: 'bills_group',
        path: '/bills/group',
        component: 'view.bills_group',
        meta: {
          title: 'bills_group',
          i18nKey: 'route.bills_group',
          constant: true
        }
      },
      {
        name: 'bills_group-accs',
        path: '/bills/group-accs',
        component: 'view.bills_group-accs',
        meta: {
          title: 'bills_group-accs',
          i18nKey: 'route.bills_group-accs',
          constant: true
        }
      },
      {
        name: 'bills_group-symbols',
        path: '/bills/group-symbols',
        component: 'view.bills_group-symbols',
        meta: {
          title: 'bills_group-symbols',
          i18nKey: 'route.bills_group-symbols',
          constant: true
        }
      },
      {
        name: 'bills_profits',
        path: '/bills/profits',
        component: 'view.bills_profits',
        meta: {
          title: 'bills_profits',
          i18nKey: 'route.bills_profits',
          constant: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      constant: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'irs',
    path: '/irs',
    component: 'layout.base',
    meta: {
      title: 'irs',
      i18nKey: 'route.irs',
      icon: 'mdi:chart-line',
      order: 4,
      constant: true
    },
    children: [
      {
        name: 'irs_monitor-discounts',
        path: '/irs/monitor-discounts',
        component: 'view.irs_monitor-discounts',
        meta: {
          title: 'irs_monitor-discounts',
          i18nKey: 'route.irs_monitor-discounts',
          constant: true
        }
      },
      {
        name: 'irs_monitor-option-ts',
        path: '/irs/monitor-option-ts',
        component: 'view.irs_monitor-option-ts',
        meta: {
          title: 'irs_monitor-option-ts',
          i18nKey: 'route.irs_monitor-option-ts',
          constant: true
        }
      },
      {
        name: 'irs_monitor-options',
        path: '/irs/monitor-options',
        component: 'view.irs_monitor-options',
        meta: {
          title: 'irs_monitor-options',
          i18nKey: 'route.irs_monitor-options',
          constant: true
        }
      },
      {
        name: 'irs_symbol-discounts',
        path: '/irs/symbol-discounts',
        component: 'view.irs_symbol-discounts',
        meta: {
          title: 'irs_symbol-discounts',
          i18nKey: 'route.irs_symbol-discounts',
          constant: true
        }
      },
      {
        name: 'irs_symbol-kpis',
        path: '/irs/symbol-kpis',
        component: 'view.irs_symbol-kpis',
        meta: {
          title: 'irs_symbol-kpis',
          i18nKey: 'route.irs_symbol-kpis',
          constant: true
        }
      },
      {
        name: 'irs_symbol-options',
        path: '/irs/symbol-options',
        component: 'view.irs_symbol-options',
        meta: {
          title: 'irs_symbol-options',
          i18nKey: 'route.irs_symbol-options',
          constant: true
        }
      },
      {
        name: 'irs_symbol-values',
        path: '/irs/symbol-values',
        component: 'view.irs_symbol-values',
        meta: {
          title: 'irs_symbol-values',
          i18nKey: 'route.irs_symbol-values',
          constant: true
        }
      },
      {
        name: 'irs_value-monitor',
        path: '/irs/value-monitor',
        component: 'view.irs_value-monitor',
        meta: {
          title: 'irs_value-monitor',
          i18nKey: 'route.irs_value-monitor',
          constant: true
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
