/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

// 手动调整为多级菜单结构，使用类型断言绕过严格的路由命名约定校验
export const generatedRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'bds',
    path: '/bds',
    component: 'layout.base',
    meta: {
      title: 'bds',
      i18nKey: 'route.bds',
      icon: 'mdi:database',
      order: 2,
      constant: true
    },
    children: [
      {
        name: 'bds_fund-data',
        path: '/bds/fund-data',
        meta: {
          title: 'bds_fund-data',
          i18nKey: 'route.bds_fund-data',
          order: 2,
          constant: true
        },
        children: [
          {
            name: 'bds_fund-data_finance-derivs',
            path: '/bds/fund-data/finance-derivs',
            component: 'view.bds_fund-data_finance-derivs',
            meta: {
              title: 'bds_fund-data_finance-derivs',
              i18nKey: 'route.bds_fund-data_finance-derivs',
              constant: true
            }
          },
          {
            name: 'bds_fund-data_fund-balances',
            path: '/bds/fund-data/fund-balances',
            component: 'view.bds_fund-data_fund-balances',
            meta: {
              title: 'bds_fund-data_fund-balances',
              i18nKey: 'route.bds_fund-data_fund-balances',
              constant: true
            }
          },
          {
            name: 'bds_fund-data_fund-cashflows',
            path: '/bds/fund-data/fund-cashflows',
            component: 'view.bds_fund-data_fund-cashflows',
            meta: {
              title: 'bds_fund-data_fund-cashflows',
              i18nKey: 'route.bds_fund-data_fund-cashflows',
              constant: true
            }
          },
          {
            name: 'bds_fund-data_fund-incomes',
            path: '/bds/fund-data/fund-incomes',
            component: 'view.bds_fund-data_fund-incomes',
            meta: {
              title: 'bds_fund-data_fund-incomes',
              i18nKey: 'route.bds_fund-data_fund-incomes',
              constant: true
            }
          }
        ]
      },
      {
        name: 'bds_index-constituents',
        path: '/bds/index-constituents',
        component: 'view.bds_index-constituents',
        meta: {
          title: 'bds_index-constituents',
          i18nKey: 'route.bds_index-constituents',
          order: 4,
          constant: true
        }
      },
      {
        name: 'bds_macro-research',
        path: '/bds/macro-research',
        component: 'layout.base',
        meta: {
          title: 'bds_macro-research',
          i18nKey: 'route.bds_macro-research',
          order: 0,
          constant: true
        },
        children: [
          {
            name: 'bds_macro-research_daily-indicators',
            path: '/bds/macro-research/daily-indicators',
            component: 'view.bds_macro-research_daily-indicators',
            meta: {
              title: 'bds_macro-research_daily-indicators',
              i18nKey: 'route.bds_macro-research_daily-indicators',
              order: 2,
              constant: true
            }
          },
          {
            name: 'bds_macro-research_economic-indicators',
            path: '/bds/macro-research/economic-indicators',
            component: 'view.bds_macro-research_economic-indicators',
            meta: {
              title: 'bds_macro-research_economic-indicators',
              i18nKey: 'route.bds_macro-research_economic-indicators',
              order: 1,
              constant: true
            }
          },
          {
            name: 'bds_macro-research_gold-reserves',
            path: '/bds/macro-research/gold-reserves',
            component: 'view.bds_macro-research_gold-reserves',
            meta: {
              title: 'bds_macro-research_gold-reserves',
              i18nKey: 'route.bds_macro-research_gold-reserves',
              order: 3,
              constant: true
            }
          }
        ]
      },
      {
        name: 'bds_market-data',
        path: '/bds/market-data',
        meta: {
          title: 'bds_market-data',
          i18nKey: 'route.bds_market-data',
          order: 3,
          constant: true
        },
        children: [
          {
            name: 'bds_market-data_daily-mktvalues',
            path: '/bds/market-data/daily-mktvalues',
            component: 'view.bds_market-data_daily-mktvalues',
            meta: {
              title: 'bds_market-data_daily-mktvalues',
              i18nKey: 'route.bds_market-data_daily-mktvalues',
              constant: true
            }
          },
          {
            name: 'bds_market-data_daily-valuations',
            path: '/bds/market-data/daily-valuations',
            component: 'view.bds_market-data_daily-valuations',
            meta: {
              title: 'bds_market-data_daily-valuations',
              i18nKey: 'route.bds_market-data_daily-valuations',
              constant: true
            }
          },
          {
            name: 'bds_market-data_index-histories',
            path: '/bds/market-data/index-histories',
            component: 'view.bds_market-data_index-histories',
            meta: {
              title: 'bds_market-data_index-histories',
              i18nKey: 'route.bds_market-data_index-histories',
              constant: true
            }
          }
        ]
      },
      {
        name: 'bds_symbol-infos',
        path: '/bds/symbol-infos',
        component: 'view.bds_symbol-infos',
        meta: {
          title: 'bds_symbol-infos',
          i18nKey: 'route.bds_symbol-infos',
          order: 5,
          constant: true
        }
      },
      {
        name: 'bds_trade-dates',
        path: '/bds/trade-dates',
        component: 'view.bds_trade-dates',
        meta: {
          title: 'bds_trade-dates',
          i18nKey: 'route.bds_trade-dates',
          order: 6,
          constant: true
        }
      }
    ]
  },
  {
    name: 'bills',
    path: '/bills',
    component: 'layout.base',
    meta: {
      title: 'bills',
      i18nKey: 'route.bills',
      icon: 'mdi:currency-cny',
      order: 3,
      constant: true
    },
    children: [
      {
        name: 'bills_bills',
        path: '/bills/bills',
        component: 'view.bills_bills',
        meta: {
          title: 'bills_bills',
          i18nKey: 'route.bills_bills',
          constant: true
        }
      },
      {
        name: 'bills_group',
        path: '/bills/group',
        component: 'view.bills_group',
        meta: {
          title: 'bills_group',
          i18nKey: 'route.bills_group',
          constant: true
        }
      },
      {
        name: 'bills_group-accs',
        path: '/bills/group-accs',
        component: 'view.bills_group-accs',
        meta: {
          title: 'bills_group-accs',
          i18nKey: 'route.bills_group-accs',
          constant: true
        }
      },
      {
        name: 'bills_group-symbols',
        path: '/bills/group-symbols',
        component: 'view.bills_group-symbols',
        meta: {
          title: 'bills_group-symbols',
          i18nKey: 'route.bills_group-symbols',
          constant: true
        }
      },
      {
        name: 'bills_profit-years',
        path: '/bills/profit-years',
        component: 'view.bills_profit-years',
        meta: {
          title: 'bills_profit-years',
          i18nKey: 'route.bills_profit-years',
          constant: true
        }
      },
      {
        name: 'bills_profits',
        path: '/bills/profits',
        component: 'view.bills_profits',
        meta: {
          title: 'bills_profits',
          i18nKey: 'route.bills_profits',
          constant: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      constant: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'irs',
    path: '/irs',
    component: 'layout.base',
    meta: {
      title: 'irs',
      i18nKey: 'route.irs',
      icon: 'mdi:chart-line',
      order: 4,
      constant: true
    },
    children: [
      {
        name: 'irs_discounts-monitor',
        path: '/irs/discounts-monitor',
        component: 'view.irs_discounts-monitor',
        meta: {
          title: 'irs_discounts-monitor',
          i18nKey: 'route.irs_discounts-monitor',
          order: 3,
          constant: true
        }
      },
      {
        name: 'irs_economic-report',
        path: '/irs/economic-report',
        component: 'view.irs_economic-report',
        meta: {
          title: 'irs_economic-report',
          i18nKey: 'route.irs_economic-report',
          order: 5,
          constant: true
        }
      },
      {
        name: 'irs_macro-framework',
        path: '/irs/macro-framework',
        component: 'view.irs_macro-framework',
        meta: {
          title: 'irs_macro-framework',
          i18nKey: 'route.irs_macro-framework',
          order: 6,
          constant: true
        }
      },
      {
        name: 'irs_option-monitor',
        path: '/irs/option-monitor',
        component: 'view.irs_option-monitor',
        meta: {
          title: 'irs_option-monitor',
          i18nKey: 'route.irs_option-monitor',
          constant: true
        }
      },
      {
        name: 'irs_option-quote',
        path: '/irs/option-quote',
        component: 'view.irs_option-quote',
        meta: {
          title: 'irs_option-quote',
          i18nKey: 'route.irs_option-quote',
          constant: true
        }
      },
      {
        name: 'irs_us-economic-dashboard',
        path: '/irs/us-economic-dashboard',
        component: 'view.irs_us-economic-dashboard',
        meta: {
          title: 'irs_us-economic-dashboard',
          i18nKey: 'route.irs_us-economic-dashboard',
          order: 7,
          constant: true
        }
      },
      {
        name: 'irs_value-monitors',
        path: '/irs/value-monitors',
        component: 'view.irs_value-monitors',
        meta: {
          title: 'irs_value-monitors',
          i18nKey: 'route.irs_value-monitors',
          order: 4,
          constant: true
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
